name: Build and Deploy Angular App

on:
  push:
    branches:
      - master  # Trigger deployment on push to the main branch
  pull_request:
    branches:
      - master  # Trigger deployment on pull requests to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.14.0'  # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build -- --prod  # Build the Angular app with production settings

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # Used for GitHub deploys
          action: "upload"
          app_location: "/"  # Location of your app's source code
          api_location: ""  # Location of your API code (if any)
          output_location: "dist"  # Location of your build output directory
